<?php

// This file contains the current being tracked configurations.

$tracked = array (
  'content_type.blog_post' => 'a859a828e643a6f294ab3e2323a6aa6b68d2ae5c',
  'field.node.body.blog_post' => 'b26e80ee2dcbd4069780d33f31f8cb3b11b93540',
  'field.node.field_new_field.blog_post' => '509b3d9c499183c6f1db5b8ffa6dd4e7903eb2c8',
  'variable.admin_theme' => '0302235c297210c67fa4b12bbda12ef63bf6d234',
  'variable.configuration_config_path' => 'e5658e2a44f0f9552808ca14933509827bb23ae8',
  'variable.field_bundle_settings_node__blog_post' => '3abd6fb48535b1e41c7d701573f2ac636c2ae305',
  'variable.node_options_blog_post' => 'cd158be13b77fa0540dc3e89ed3cc696dd1c18de',
  'variable.node_preview_blog_post' => '00cd637d5fd3dc0d40a4f6db57174e10838adae5',
  'variable.node_submitted_blog_post' => 'fb29ded26afd3db962900d3ab78aeef1444510a3',
  'variable.site_mail' => '3b72b09501c69aa76e32d6febbb14a2f482457ea',
  'variable.site_name' => 'd69c87bc4b975aece814c0c893fd835e503493aa',
  'permission.create_blog_post_content' => '168f3e682af6914d2a09fe4c09c9a6e04da21c3e',
  'permission.delete_any_blog_post_content' => 'ae900e31d28b23d07d89fe920455c49805726184',
  'permission.delete_own_blog_post_content' => 'a0a67b83479201bb4e478775c4cf4f9dc7e76d95',
  'permission.edit_any_blog_post_content' => 'f9d44f4fe45dcdd1b71be68d3cc5b6d2657540f9',
  'permission.edit_own_blog_post_content' => '0274c78b01d3c3d3fc7e01e995577b120edcbb49',
);


// The following modules are required to run the configurations of this file.

$modules = array(
  'node',
  'field_sql_storage',
  'text',
);
