<?php

// This file contains the current being tracked configurations.

$tracked = array (
  'content_type.blog_post' => 'ba2fb05d50b70bb4cd7c1c4fa6723ae4dd39cd0b',
  'field.node.body.blog_post' => '62340572635691202e591db4b4149103d3f7362c',
  'variable.configuration_config_path' => 'e5658e2a44f0f9552808ca14933509827bb23ae8',
  'variable.site_mail' => '3b72b09501c69aa76e32d6febbb14a2f482457ea',
  'variable.site_name' => 'd69c87bc4b975aece814c0c893fd835e503493aa',
);


// The following modules are required to run the configurations of this file.

$modules = array(
);
